--Cài đặt lược đồ CSDL trên, khai báo khóa chính, khóa ngoại--
CREATE TABLE NHANVIEN(
	MANV VARCHAR(3) CONSTRAINT NV_MANV_PK PRIMARY KEY,
	HOTEN VARCHAR(40) CONSTRAINT NV_HOTEN_NN NOT NULL,
	NGSINH SMALLDATETIME,
	PHAI VARCHAR(3),
	DIACHI VARCHAR(50),
	MAPHG VARCHAR(2),
	LUONG MONEY
)

CREATE TABLE PHONGBAN(
	MAPHG VARCHAR(2) CONSTRAINT PB_MAPHG_PK PRIMARY KEY,
	TENPHG VARCHAR(50),
	TRPHG VARCHAR(3) CONSTRAINT PB_TGPHG_FK FOREIGN KEY(TRPHG) REFERENCES NHANVIEN(MANV),
	NGNC SMALLDATETIME
)

CREATE TABLE DEAN(
	MADA VARCHAR(5) CONSTRAINT DA_MADA_PK PRIMARY KEY,
	TENDA VARCHAR(50) CONSTRAINT DA_TENDA_NN NOT NULL,
	DDIEM_DA VARCHAR(50),
	MAPHG VARCHAR(2) CONSTRAINT DA_MAPHG_FK FOREIGN KEY(MAPHG) REFERENCES PHONGBAN(MAPHG),
	NGBD_DK SMALLDATETIME,
	NGKT_DK SMALLDATETIME
)

CREATE TABLE PHANCONG(
	MANV VARCHAR(3),
	MADA VARCHAR(5),
	THOIGIAN INT
	CONSTRAINT PHANCONG_MANV_MADA_PK PRIMARY KEY,
	CONSTRAINT PHANCONG_MANV_FK FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV),
	CONSTRAINT PHANCONG_MADA_FK FOREIGN KEY(MADA) REFERENCES DEAN(MADA)

)

ALTER TABLE NHANVIEN
ADD CONSTRAINT NV_MAPHG_FK FOREIGN KEY(MAPHG) REFERENCES PHONGBAN(MAPHG)

--Câu 3. Thực hiện các truy vấn--
--a.Cho biết tên phòng ban (TENPHG) có mức lương trung bình từ 24.000.000 trở lên, sắp xếp theo tên phòng ban giảm dần. (1.0 điểm)
SELECT TENPHGFROM PHONGBAN, NHANVIENWHERE NHANVIEN.MAPHG = PHONGBAN.MAPHGGROUP BY TENPHGHAVING AVG(LUONG)>=24000000ORDER BY TENPHG DESC--b. Liệt kê thông tin nhân viên (HOTEN) tham gia đề án của phòng “Nghien Cuu” có địa điểm thực hiện đề án tại “HANOI”. (1.0 điểm)SELECT HOTENFROM NHANVIEN NV, PHONGBAN PB, PHANCONG PC, DEAN DAWHERE PC.MANV = NV.MANV	AND PC.MADA = DA.MADA	AND DA.MAPHG = PB.MAPHG	AND PB.TENPHG = 'NGHIEN CUU'	AND DA.DDIEM_DA = 'HANOI'--c. Liệt kê tên nhân viên (HOTEN) và số đề án mà nhân viên đó tham gia. (1.0 điểm)
SELECT NHANVIEN.HOTEN, COUNT(PHANCONG.MADA) AS SOLUONGDEAN
FROM PHANCONG, NHANVIEN
WHERE PHANCONG.MANV = NHANVIEN.MANV
GROUP BY NHANVIEN.HOTEN

--d. Tìm nhân viên (HOTEN) chỉ tham gia những đề án do phòng “Nghien Cuu” chủ trì. (1.0 điểm)
SELECT HOTEN
FROM NHANVIEN NV, PHANCONG PC
WHERE NV.MANV = PC.MANV
EXCEPT
SELECT HOTEN
FROM NHANVIEN NV, PHANCONG PC, DEAN DA, PHONGBAN PB
WHERE NV.MANV = PC.MANV
	AND PC.MADA = DA.MADA
	AND DA.MAPHG = PB.MAPHG
	AND PB.TENPHG != 'NGHIEN CUU'
