
CREATE TABLE KHOA(
	MAKHOA VARCHAR(4) CONSTRAINT KHOA_MAKHOA_PK PRIMARY KEY,
	TENKHOA VARCHAR(40) CONSTRAINT KHOA_MAKHOA_NN NOT NULL,
	NGTLAP SMALLDATETIME,
	TRGKHOA CHAR(4)
)

CREATE TABLE MONHOC(
	MAMH VARCHAR(10)  CONSTRAINT MH_MAMH_PK PRIMARY KEY,
	TENMH VARCHAR(40) CONSTRAINT MH_TENMH_NN NOT NULL,
	TCLT TINYINT,
	TCTH TINYINT,
	MAKHOA VARCHAR(4) CONSTRAINT MH_MAKHOA_FK FOREIGN KEY (MAKHOA) REFERENCES KHOA (MAKHOA),
)

CREATE TABLE DIEUKIEN(
	MAMH VARCHAR(10),
	MAMH_TRUOC VARCHAR(10),
	CONSTRAINT DK_MAMH_MAMHTRUOC_PK PRIMARY KEY(MAMH, MAMH_TRUOC),
	CONSTRAINT DK_MAMH_FK FOREIGN KEY(MAMH) REFERENCES MONHOC(MAMH),
	CONSTRAINT DK_MAMH_TRUOC_FK FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)
)

CREATE TABLE GIAOVIEN(
	MAGV CHAR(4) CONSTRAINT GV_MAGV_PK PRIMARY KEY,
	HOTEN VARCHAR(40) CONSTRAINT GV_HOTEN_NN NOT NULL,
	HOCVI VARCHAR(10),
	HOHAM VARCHAR(10),
	GIOITINH VARCHAR(3),
	NGVL SMALLDATETIME,
	HESO NUMERIC(4,2),
	MUCLUONG MONEY, 
	MAKHOA VARCHAR(4),
	CONSTRAINT GV_MAKHOA_FK FOREIGN KEY(MAKHOA) REFERENCES KHOA(MAKHOA)
)

CREATE TABLE LOP(
	MALOP CHAR(3) CONSTRAINT LOP_MALOP_PK PRIMARY KEY,
	TENLOP VARCHAR(40) CONSTRAINT LOP_TENLOP_NN NOT NULL,
	TRGLOP CHAR(5),
	SISO TINYINT,
	MAGVCN CHAR(4) CONSTRAINT LOP_MAGVCN_FK FOREIGN KEY(MAGVCN) REFERENCES GIAOVIEN(MAGV)
)

CREATE TABLE HOCVIEN(
	MAHV CHAR(5) CONSTRAINT HV_MAHV_PK PRIMARY KEY,
	HO VARCHAR(40) CONSTRAINT HV_HO_NN NOT NULL,
	TEN VARCHAR(40) CONSTRAINT HV_TEN_NN NOT NULL,
	NGSINH SMALLDATETIME,
	GIOITINH VARCHAR(3),
	NOISINH VARCHAR(40),
	MALOP CHAR(3) CONSTRAINT HV_MALOP_FK FOREIGN KEY(MALOP) REFERENCES LOP(MALOP) 
)


CREATE TABLE GIANGDAY(
	MALOP CHAR(3),
	MAMH VARCHAR (10),
	MAGV CHAR(4),
	HOCKY TINYINT,
	NAM SMALLINT,
	TUNGAY SMALLDATETIME,
	DENNGAY SMALLDATETIME,
	CONSTRAINT GD_MALOP_MAMH_PK PRIMARY KEY(MALOP,MAMH),
	CONSTRAINT GD_MAGV_FK FOREIGN KEY(MAGV) REFERENCES GIAOVIEN(MAGV),
	CONSTRAINT GD_MAMH_FK FOREIGN KEY(MAMH) REFERENCES MONHOC(MAMH),
	CONSTRAINT GD_MALOP_FK FOREIGN KEY(MALOP) REFERENCES LOP(MALOP)
);

CREATE TABLE KETQUATHI(
	MAHV CHAR(5), 
	MAMH VARCHAR(10),
	LANTHI TINYINT,
	NGTHI SMALLDATETIME,
	DIEM NUMERIC(4,2),
	KQUA VARCHAR(10),
	CONSTRAINT KQ_MAHV_MAMH_PK PRIMARY KEY(MAMH, MAHV),
	CONSTRAINT KQ_MAHV_FK FOREIGN KEY(MAHV) REFERENCES HOCVIEN(MAHV),
	CONSTRAINT KQ_MAMH_FK FOREIGN KEY(MAMH) REFERENCES MONHOC(MAMH)
)
ALTER TABLE KHOA
ADD CONSTRAINT KHOA_TRGKHOA_FK FOREIGN KEY (TRGKHOA) REFERENCES GIAOVIEN(MAGV)

ALTER TABLE LOP
ADD CONSTRAINT LOP_TRGLOP_FK FOREIGN KEY (TRGLOP) REFERENCES HOCVIEN(MAHV)

ALTER TABLE HOCVIEN
ADD GHICHU VARCHAR(100),
	DIEMTB NUMERIC(4,2),
	XEPLOAI VARCHAR(20)


