CREATE TABLE NHANVIEN(
	MANV VARCHAR(3) CONSTRAINT NV_MANV_PK PRIMARY KEY,
	HOTEN VARCHAR(40) CONSTRAINT NV_HOTEN_NN NOT NULL,
	NGSINH SMALLDATETIME,
	PHAI VARCHAR(3),
	DIACHI VARCHAR(50),
	MAPHG VARCHAR(2),
	LUONG MONEY
)

CREATE TABLE PHONGBAN(
	MAPHG VARCHAR(2) CONSTRAINT PB_MAPHG_PK PRIMARY KEY,
	TENPHG VARCHAR(50),
	TRPHG VARCHAR(3) CONSTRAINT PB_TGPHG_FK FOREIGN KEY(TRPHG) REFERENCES NHANVIEN(MANV),
	NGNC SMALLDATETIME
)

CREATE TABLE DEAN(
	MADA VARCHAR(5) CONSTRAINT DA_MADA_PK PRIMARY KEY,
	TENDA VARCHAR(50) CONSTRAINT DA_TENDA_NN NOT NULL,
	DDIEM_DA VARCHAR(50),
	MAPHG VARCHAR(2) CONSTRAINT DA_MAPHG_FK FOREIGN KEY(MAPHG) REFERENCES PHONGBAN(MAPHG),
	NGBD_DK SMALLDATETIME,
	NGKT_DK SMALLDATETIME
)

CREATE TABLE PHANCONG(
	MANV VARCHAR(3),
	MADA VARCHAR(5),
	THOIGIAN INT
	CONSTRAINT PHANCONG_MANV_MADA_PK PRIMARY KEY,
	CONSTRAINT PHANCONG_MANV_FK FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV),
	CONSTRAINT PHANCONG_MADA_FK FOREIGN KEY(MADA) REFERENCES DEAN(MADA)

)

ALTER TABLE NHANVIEN
ADD CONSTRAINT NV_MAPHG_FK FOREIGN KEY(MAPHG) REFERENCES PHONGBAN(MAPHG)
